on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write

jobs:
  test-report:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v2

      - name: Node.js 세팅
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: 패키지 설치
        run: |
          yarn

      - name: 테스트 실행
        run: |
          yarn test

      - name: 테스트 결과 발행2
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Tests # Name of the check run which will be created
          path: reports/*.xml # Path to test results
          reporter: jest-junit
